CREATE TABLE SourceDocument (
 Url TEXT PRIMARY KEY, Title TEXT NOT NULL, Text TEXT NOT NULL, FetchedAt TEXT NOT NULL
);
ALTER TABLE Outreach ADD COLUMN EvidenceJson TEXT NOT NULL DEFAULT '[]';
ALTER TABLE Outreach ADD COLUMN ProfileId TEXT REFERENCES UserProfile(Id);
ALTER TABLE Outreach ADD COLUMN Revision INTEGER NOT NULL DEFAULT 1;
